CREATE DATABASE IF NOT EXISTS wp;
CREATE USER IF NOT EXISTS 'djanusz'@'%' IDENTIFIED BY 'djanusz1234';
GRANT ALL PRIVILEGES ON wp.* TO 'djanusz'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1234';
